### ISSUE TITLE
Shop giving far too much profit

### ISSUE THREAD

**Issue by michael-hart** [FullStackJones/BigBrainCurrency#23]
I just collected profits from my certus quartz shop. I estimate that it should have been 33 silver based on the amount sold, but instead I collected 3 brain coins and 6 gold coin, equivalent to 297 silver. This seems... not right!

**Comment by FullStackJones** [comment]
looks like this specifically happens when getting the coins out of the shop by the money pouch. my guess is i inverted the coin list should hopefully be a easy fix

**Comment by michael-hart** [comment]
I think it's more likely that the slots are off by one but in the correct order. In my case, I should have received 3 gold and 6 silver, but instead got 3 brain and 6 gold - that's shifted by 1, not inverted :)

**Comment by FullStackJones** [comment]
this should be fixed once the shop improvements branch is merged in :)

**Comment by FullStackJones** [comment]
should be resolved in v1.1.3
