### ISSUE TITLE
Shift clicking items in deposits them into the 'amount for sale' slot

### ISSUE THREAD

**Issue by Mathstormind** [FullStackJones/BigBrainCurrency#25]
When you have an item in the for sale slot, regardless of price, shift clicking any of the same items into the stock inventory will fill the for sale slot when any of the stock inventory stacks are filled completely (shift-clicking 64 in will deposit into the for sale, while filling a stack (32 in stock, shifting 32 in) will first go into inventory)

**Comment by FullStackJones** [comment]
with the refactor in v1.2 this slot no longer exists. closing this issue.
