### ISSUE TITLE
Shops not auto converting when profit stack is full.

### ISSUE THREAD

**Issue by Mathstormind** [FullStackJones/BigBrainCurrency#28]
When you've earned more than 99 of any coins, the shop appears to void the rest of the coins earned, instead of converting the stack, or a portion of the stack, to the next up currency.

maybe it would be helpful to always try to divide the coins by 9, up until brain level, so you can easily see how much money you have made?

**Comment by FullStackJones** [comment]
ill take a look i may have forgotten to add the conversion for going up rather than down

**Comment by FullStackJones** [comment]
The way profit has been changed as of v1.2 so this no longer applies closeing issue
