### ISSUE TITLE
Modular routers Dupe

### ISSUE THREAD

**Issue by Mathstormind** [FullStackJones/BigBrainCurrency#29]
As the title says, if you put a modular router with an activator module next to the brain bank (and have the activator module right click)
it will pull out 3 copper, for free. this will only pull out 3, but if you replace the router, it will pull another 3 copper.

**Comment by FullStackJones** [comment]
Going to mark this as not being fixed as brain banks are being reworked in the next update, so this will not apply

**Comment by FullStackJones** [comment]
new block specific data handling added to v1.2 this should now be resolved
