### ISSUE TITLE
Money Generator

### ISSUE THREAD

**Issue by Mathstormind** [FullStackJones/BigBrainCurrency#32]
Allthemods10, specific mod "GatewaysToEternity' 

the afforementioned mod allows you to spawn a  few hordes of enemies at a time (automatable) in turn for some rewards, one of these rewards is dungeon rolls. 
![image](https://github.com/user-attachments/assets/81a9fc98-f8aa-43ff-8157-fcd5b13f4687)

using some routers i was able to farm 33 gold coins in under 1 hour.

**Comment by FullStackJones** [comment]
not going to fix this, its up to big brain smp or modpack authors to stop this.
